#version: '3'
services:

  nginx-flask-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx-flask-backend           # custom name shows for when you run docker images
    ports:
      - "5000:5000"
    container_name: nginx-flask-backend
